version = 0.1

[default.deploy.parameters]
stack_name = "job-application-smi-back-end"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
confirm_auth_without_auth = true
